from __future__ import annotations

import json
import math
import os
import platform
import random
import subprocess
import sys
import threading
import time
from pathlib import Path

import psutil
from PyQt6.QtCore import (QPropertyAnimation, QEasingCurve, QMimeData, QObject, QPointF, QRectF,
                          QSize, Qt, QTimer, QUrl, pyqtSignal)
from PyQt6.QtGui import (QBrush, QColor, QDragEnterEvent, QDropEvent, QFont,
                         QFontDatabase, QKeySequence, QLinearGradient,
                         QPainter, QPainterPath, QPen, QPixmap,
                         QRadialGradient, QShortcut)
from PyQt6.QtWidgets import (QApplication, QFileDialog, QFrame, QHBoxLayout,
                             QLabel, QLineEdit, QMainWindow, QProgressBar,
                             QPushButton, QScrollArea, QSizePolicy, QTextEdit,
                             QVBoxLayout, QWidget, QGraphicsDropShadowEffect)


def _base_dir() -> Path:
    if getattr(sys, "frozen", False):
        return Path(sys.executable).parent
    return Path(__file__).resolve().parent


BASE_DIR = _base_dir()
CONFIG_DIR = BASE_DIR / "config"
API_FILE = CONFIG_DIR / "api_keys.json"

_DEFAULT_W, _DEFAULT_H = 980, 700
_MIN_W, _MIN_H = 820, 580
_LEFT_W = 148
_RIGHT_W = 340

_OS = platform.system()  # "Windows" | "Darwin" | "Linux"


class C:
    BG = "#0A0A0A"          # Deep obsidian background
    PANEL = "#111111"       # Slightly lighter for panels
    PANEL2 = "#1A1A1A"      # For hover/active states
    BORDER = "#2A2A2A"      # Subtle grey borders
    BORDER_B = "#333333"
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
                if r.returncode == 0:
                    for line in r.stdout.strip().split("\n"):
                        parts = line.split(",")
                        if len(parts) >= 2:
                            try:
                                return float(parts[1].strip().replace("%", ""))
                            except ValueError:
                                pass
            except Exception:
                pass

            # Intel GPU (Linux)
            try:
                r = subprocess.run(
                    ["intel_gpu_top", "-J", "-s", "500"],
                    capture_output=True,
                    text=True,
                    timeout=1,
                )
                if r.returncode == 0 and "Render/3D" in r.stdout:
                    import re

                    m = re.search(r'"busy":\s*([\d.]+)', r.stdout)
                    if m:
                        return float(m.group(1))
            except Exception:
                pass

        # macOS — powermetrics (GPU Engine)
        if _OS == "Darwin":
            try:
                r = subprocess.run(
                    [
                        "sudo",
                        "-n",
                        "powermetrics",
                        "-n",
                        "1",
                        "-i",
                        "500",
                        "--samplers",
                        "gpu_power",
                    ],
                    capture_output=True,
                    text=True,
                    timeout=2,
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
    **dict.fromkeys(
        ["mp3", "wav", "ogg", "m4a", "aac", "flac", "wma", "opus"], "audio"
    ),
    **dict.fromkeys(["pdf"], "pdf"),
    **dict.fromkeys(["doc", "docx"], "word"),
    **dict.fromkeys(["xls", "xlsx", "ods"], "excel"),
    **dict.fromkeys(["ppt", "pptx"], "pptx"),
    **dict.fromkeys(
        [
            "py",
            "js",
            "ts",
            "jsx",
            "tsx",
            "html",
            "css",
            "java",
            "c",
            "cpp",
            "cs",
            "go",
            "rs",
            "rb",
            "php",
            "swift",
            "kt",
            "sh",
            "sql",
            "lua",
        ],
        "code",
    ),
    **dict.fromkeys(["zip", "rar", "tar", "gz", "7z", "bz2", "xz"], "archive"),
    **dict.fromkeys(["txt", "md", "rst", "log"], "text"),
    **dict.fromkeys(["csv", "tsv", "json", "xml"], "data"),
}


def _file_category(path: Path) -> str:
    return _EXT_TO_CAT.get(path.suffix.lower().lstrip("."), "unknown")


def _fmt_size(size: int) -> str:
    if size < 1024:
        return f"{size} B"
    elif size < 1024**2:
        return f"{size/1024:.1f} KB"
    elif size < 1024**3:
        return f"{size/1024**2:.1f} MB"
    else:
        return f"{size/1024**3:.1f} GB"


class FileDropZone(QWidget):
    file_selected = pyqtSignal(str)

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setAcceptDrops(True)
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
        self._update_metrics()

        self._log_sig.connect(self._log.append_log)
        self._state_sig.connect(self._apply_state)
        self._ui_cmd_sig.connect(self._handle_ui_cmd)
        self._phone_sig.connect(self._handle_phone_conn)

        self._overlay: SetupOverlay | None = None
        self._ready = self._check_config()
        if not self._ready:
            self._show_setup()

        sc_mute = QShortcut(QKeySequence("F4"), self)
        sc_mute.activated.connect(self._toggle_mute)
        sc_full = QShortcut(QKeySequence("F11"), self)
        sc_full.activated.connect(self._toggle_fullscreen)

    def _toggle_fullscreen(self):
        if self.isFullScreen():
            self.showNormal()
        else:
            self.showFullScreen()

    def resizeEvent(self, event):
        super().resizeEvent(event)
        cw = self.centralWidget()
        pw, ph = cw.width(), cw.height()
        if hasattr(self, '_left_panel'):
            self._left_panel.update_geometry(pw, ph)
        if hasattr(self, '_right_panel'):
            self._right_panel.update_geometry(pw, ph)
        if self._overlay and self._overlay.isVisible():
            ow, oh = 460, 390
            self._overlay.setGeometry(
                (cw.width() - ow) // 2,
                (cw.height() - oh) // 2,
                ow,
                oh,
            )
        if self._remote_overlay and self._remote_overlay.isVisible():
            ow, oh = RemoteKeyOverlay._OW, RemoteKeyOverlay._OH
            self._remote_overlay.setGeometry(
                (cw.width() - ow) // 2,
                (cw.height() - oh) // 2,
                ow,
                oh,
            )

    
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
        if net < 1.0:
            net_str = f"{net*1024:.0f}KB/s"
        else:
            net_str = f"{net:.1f}MB/s"
        net_pct = min(100, net * 10)  # 10 MB/s = %100
        self._bar_net.set_value(net_pct, net_str)

        # GPU
        gpu = snap["gpu"]
        if gpu >= 0:
            self._bar_gpu.set_value(gpu, f"{gpu:.0f}%")
        else:
            self._bar_gpu.set_value(0, "N/A")

        # TMP
        tmp = snap["tmp"]
        if tmp >= 0:
            tmp_pct = min(100, (tmp / 100) * 100)
            self._bar_tmp.set_value(tmp_pct, f"{tmp:.0f}°C")
        else:
            self._bar_tmp.set_value(0, "N/A")

        try:
            boot_t = psutil.boot_time()
            elapsed = time.time() - boot_t
            h = int(elapsed // 3600)
            m = int((elapsed % 3600) // 60)
            self._uptime_lbl.setText(f"UP  {h:02d}:{m:02d}")
        except Exception:
            self._uptime_lbl.setText("UP  --:--")

        try:
            proc_count = len(psutil.pids())
            self._proc_lbl.setText(f"PROC  {proc_count}")
        except Exception:
            self._proc_lbl.setText("PROC  --")


    def _handle_ui_cmd(self, cmd: str):
        if cmd == "sys":
            self._left_panel.toggle()
        elif cmd == "log":
            self._right_panel.toggle()

    def toggle_sys_monitor(self):

        self._left_panel.toggle()
        
    def toggle_activity_log(self):
        self._right_panel.toggle()

    def _build_header(self) -> QWidget:
        w = QWidget()
        w.setFixedHeight(54)
        w.setStyleSheet(f"background: {C.DARK}; border-bottom: 1px solid {C.BORDER_B};")
        lay = QHBoxLayout(w)
        lay.setContentsMargins(16, 0, 16, 0)

        def _badge(txt, color=C.TEXT_MED):
            l = QLabel(txt)
            l.setFont(QFont("Courier New", 8))
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
# MISSING LINE
